//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTC2154801010010.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiayChiTiet
    {
        public int id { get; set; }
        public string TenGiay { get; set; }
        public string Mau { get; set; }
        public int Soluong { get; set; }
        public decimal Gia { get; set; }
        public int TTGiay { get; set; }
    
        public virtual ThongTinGiay ThongTinGiay { get; set; }
    }
}
